# Generated by Django 6.0.2 on 2026-03-21 07:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_usuario_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudrecuperacioncuenta',
            options={'ordering': ['-creada_en'], 'verbose_name': 'Solicitud de recuperación de cuenta', 'verbose_name_plural': 'Solicitudes de recuperación de cuenta'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveIndex(
            model_name='solicitudrecuperacioncuenta',
            name='principal_s_token_08c151_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitudrecuperacioncuenta',
            name='principal_s_usuario_4ed777_idx',
        ),
        migrations.RenameField(
            model_name='solicitudrecuperacioncuenta',
            old_name='activo',
            new_name='activa',
        ),
        migrations.RenameField(
            model_name='solicitudrecuperacioncuenta',
            old_name='usado_en',
            new_name='usada_en',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
        migrations.AddField(
            model_name='solicitudrecuperacioncuenta',
            name='creada_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='principal/usuarios/avatar/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='institucion',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='solicitudrecuperacioncuenta',
            name='expira_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudrecuperacioncuenta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitudrecuperacioncuenta',
            name='token',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='solicitudrecuperacioncuenta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recuperacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COOR', 'Coordinador'), ('EVAL', 'Evaluador'), ('PON', 'Ponente'), ('PART', 'Participante')], default='PART', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RemoveField(
            model_name='solicitudrecuperacioncuenta',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='solicitudrecuperacioncuenta',
            name='ip_origen',
        ),
        migrations.RemoveField(
            model_name='solicitudrecuperacioncuenta',
            name='user_agent',
        ),
    ]
