# Generated by Django 6.0.2 on 2026-03-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COOR', 'Coordinador'), ('EVAL', 'Evaluador'), ('PON', 'Ponente'), ('PART', 'Participante')], default='PART', max_length=10),
        ),
    ]
