# Generated by Django 6.0.2 on 2026-03-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudrecuperacioncuenta',
            options={'ordering': ['-creada_en'], 'verbose_name': 'solicitud de recuperación', 'verbose_name_plural': 'solicitudes de recuperación'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.RemoveField(
            model_name='solicitudrecuperacioncuenta',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='solicitudrecuperacioncuenta',
            name='token',
        ),
        migrations.RemoveField(
            model_name='solicitudrecuperacioncuenta',
            name='usada_en',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='institucion',
        ),
        migrations.AddField(
            model_name='solicitudrecuperacioncuenta',
            name='usada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/'),
        ),
        migrations.AlterField(
            model_name='solicitudrecuperacioncuenta',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COORDINADOR', 'Coordinador'), ('EVALUADOR', 'Evaluador'), ('PONENTE', 'Ponente'), ('PARTICIPANTE', 'Participante')], db_index=True, default='PARTICIPANTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
