# Generated by Django 6.0.2 on 2026-03-21 08:45

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_solicitudrecuperacioncuenta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudrecuperacioncuenta',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='solicitudrecuperacioncuenta',
            name='creada_en',
        ),
        migrations.RemoveField(
            model_name='solicitudrecuperacioncuenta',
            name='usada',
        ),
        migrations.AddField(
            model_name='solicitudrecuperacioncuenta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitudrecuperacioncuenta',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitudrecuperacioncuenta',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrecuperacioncuenta',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='solicitudrecuperacioncuenta',
            name='usado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrecuperacioncuenta',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solicitudrecuperacioncuenta',
            name='expira_en',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 8, 45, 21, 849772, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudrecuperacioncuenta',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudrecuperacioncuenta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COOR', 'Coordinador'), ('EVAL', 'Evaluador/Jurado'), ('PON', 'Ponente'), ('PART', 'Participante')], db_index=True, default='PART', help_text='Rol base operativo (redirección por módulo y control general).', max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono'),
        ),
        migrations.AddIndex(
            model_name='solicitudrecuperacioncuenta',
            index=models.Index(fields=['token'], name='principal_s_token_08c151_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudrecuperacioncuenta',
            index=models.Index(fields=['usuario', 'activo'], name='principal_s_usuario_4ed777_idx'),
        ),
    ]
