# Generated by Django 6.0.2 on 2026-03-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_solicitudrecuperacioncuenta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='apellido materno'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='apellido paterno'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='nombres'),
        ),
    ]
