# Generated by Django 6.0.2 on 2026-03-05 19:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import ponente.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=240)),
                ('tipo', models.CharField(blank=True, default='', max_length=120)),
                ('area_tematica', models.CharField(blank=True, default='', max_length=160)),
                ('resumen', models.TextField(blank=True, default='')),
                ('autores', models.TextField(blank=True, default='')),
                ('archivo_resumen', models.FileField(blank=True, null=True, upload_to=ponente.models.upload_resumen, validators=[django.core.validators.FileExtensionValidator(['pdf']), ponente.models.validate_resumen_size])),
                ('presentacion', models.FileField(blank=True, null=True, upload_to=ponente.models.upload_presentacion, validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx']), ponente.models.validate_presentacion_size])),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EN_REVISION', 'En revisión'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='REGISTRADA', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponencias_ponente', to='administrador.evento')),
                ('ponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponencias_creadas_ponente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado_en', '-id'],
                'indexes': [models.Index(fields=['evento', 'ponente'], name='ponente_pon_evento__1f5567_idx'), models.Index(fields=['estado'], name='ponente_pon_estado_d3fade_idx')],
            },
        ),
    ]
