# Generated by Django 6.0.2 on 2026-03-05 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador', '0002_actividadcronograma_espacio_evaluacionasignacion_and_more'),
        ('ponente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='evaluacion_proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponencia_origen', to='evaluador.evaluacionproyecto'),
        ),
    ]
