# Generated by Django 6.0.2 on 2026-03-06 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('ponente', '0002_ponencia_evaluacion_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponencia',
            name='evaluacion_proyecto',
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponencias', to='administrador.evento'),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='ponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ponencia',
            constraint=models.UniqueConstraint(fields=('evento', 'ponente', 'titulo'), name='uq_ponencia_evento_ponente_titulo'),
        ),
    ]
