# Generated by Django 6.0.2 on 2026-03-06 05:09

import django.core.validators
import ponente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponente', '0003_remove_ponencia_evaluacion_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='cv_documento',
            field=models.FileField(blank=True, null=True, upload_to=ponente.models.upload_cv, validators=[django.core.validators.FileExtensionValidator(['pdf']), ponente.models.validate_pdf_size]),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='cv_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('VALIDADO', 'Validado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='diapositivas_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('VALIDADO', 'Validado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='diapositivas_presentacion',
            field=models.FileField(blank=True, null=True, upload_to=ponente.models.upload_diapositivas, validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx']), ponente.models.validate_presentacion_size]),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='requerimientos_tecnicos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='resena_biografica',
            field=models.FileField(blank=True, null=True, upload_to=ponente.models.upload_resena, validators=[django.core.validators.FileExtensionValidator(['pdf']), ponente.models.validate_pdf_size]),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='resena_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('VALIDADO', 'Validado')], default='PENDIENTE', max_length=20),
        ),
    ]
