# Generated by Django 6.0.2 on 2026-03-06 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('ponente', '0004_ponencia_cv_documento_ponencia_cv_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='espacio_asignado',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='estado_programacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ponencia',
            index=models.Index(fields=['fecha_programada'], name='ponente_pon_fecha_p_6f805b_idx'),
        ),
        migrations.AddIndex(
            model_name='ponencia',
            index=models.Index(fields=['estado_programacion'], name='ponente_pon_estado__058673_idx'),
        ),
    ]
