# Generated by Django 6.0.2 on 2026-03-08 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('evaluador', '0002_actividadcronograma_espacio_evaluacionasignacion_and_more'),
        ('ponente', '0006_ponencia_evaluacion_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ponencia',
            name='constancia_generada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='constancia_habilitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ponencia',
            name='folio_constancia',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='ponencia',
            index=models.Index(fields=['constancia_habilitada'], name='ponente_pon_constan_c3117d_idx'),
        ),
    ]
