# Generated by Django 6.0.2 on 2026-03-17 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('evaluador', '0002_actividadcronograma_espacio_evaluacionasignacion_and_more'),
        ('ponente', '0007_ponencia_constancia_generada_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ponencia',
            name='uq_ponencia_evento_ponente_titulo',
        ),
        migrations.AddConstraint(
            model_name='ponencia',
            constraint=models.UniqueConstraint(fields=('evento', 'ponente'), name='uq_ponencia_evento_ponente'),
        ),
    ]
