# Generated by Django 6.0.2 on 2026-03-22 19:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import ponente.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponente', '0008_remove_ponencia_uq_ponencia_evento_ponente_titulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPonente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('institucion', models.CharField(blank=True, default='', max_length=180)),
                ('especialidad', models.CharField(blank=True, default='', max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=ponente.models.upload_avatar_perfil, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('cv', models.FileField(blank=True, null=True, upload_to=ponente.models.upload_cv_perfil, validators=[django.core.validators.FileExtensionValidator(['pdf']), ponente.models.validate_pdf_size])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ponente_sigep', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de ponente',
                'verbose_name_plural': 'Perfiles de ponentes',
            },
        ),
    ]
