# Generated by Django 6.0.2 on 2026-03-03 01:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinador', '0009_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada')], default='BORRADOR', max_length=12)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='coordinador.evaluacionasignacion')),
            ],
            options={
                'indexes': [models.Index(fields=['estado'], name='evaluador_e_estado_8ef31e_idx'), models.Index(fields=['enviada_en'], name='evaluador_e_enviada_91b985_idx')],
            },
        ),
    ]
