# Generated by Django 6.0.2 on 2026-03-04 23:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import evaluador.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('evaluador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('responsable', models.CharField(blank=True, default='', max_length=180)),
            ],
            options={
                'ordering': ['inicio', 'fin', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('AUDITORIO', 'Auditorio'), ('SALA', 'Sala'), ('LABORATORIO', 'Laboratorio'), ('OTRO', 'Otro')], default='SALA', max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=220)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('tags', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ['-actualizado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=220)),
                ('ponente', models.CharField(blank=True, default='', max_length=180)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('lugar', models.CharField(blank=True, default='', max_length=180)),
            ],
            options={
                'ordering': ['inicio', 'fin', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COORDINADOR', 'Coordinador'), ('USUARIO', 'Usuario'), ('EVALUADOR', 'Evaluador'), ('PONENTE', 'Ponente'), ('PARTICIPANTE', 'Participante')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('puesto', models.CharField(blank=True, default='', max_length=120)),
                ('institucion', models.CharField(blank=True, default='', max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=evaluador.models._avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), evaluador.models.validate_avatar_size])),
                ('cv', models.FileField(blank=True, null=True, upload_to=evaluador.models._cv_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), evaluador.models.validate_cv_size])),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=220)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(choices=[('TODOS', 'Todos'), ('INSCRIPCIONES', 'Inscripciones'), ('EVALUACIONES', 'Evaluaciones'), ('ASISTENCIA', 'Asistencia'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel (XLSX)')], default='PDF', max_length=10)),
                ('modo', models.CharField(choices=[('TIEMPO_REAL', 'Tiempo real'), ('HISTORIAL', 'Historial')], default='TIEMPO_REAL', max_length=20)),
                ('estado', models.CharField(choices=[('LISTO', 'Listo'), ('ARCHIVADO', 'Archivado')], default='LISTO', max_length=20)),
                ('generado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=evaluador.models.reporte_upload_path)),
            ],
            options={
                'ordering': ['-generado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=220)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa')], default='BORRADOR', max_length=20)),
            ],
            options={
                'ordering': ['-actualizado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RubricaAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to=evaluador.models.rubrica_upload_path)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('tamano', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RubricaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('puntaje_max', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='evaluacionentrega',
            options={'ordering': ['-fecha_envio', '-actualizado_en', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='evaluacionentrega',
            name='evaluador_e_enviada_91b985_idx',
        ),
        migrations.RenameField(
            model_name='evaluacionentrega',
            old_name='updated_at',
            new_name='actualizado_en',
        ),
        migrations.RenameField(
            model_name='evaluacionentrega',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='evaluacionentrega',
            old_name='enviada_en',
            new_name='fecha_envio',
        ),
        migrations.RenameField(
            model_name='evaluacionentrega',
            old_name='observaciones',
            new_name='observaciones_generales',
        ),
        migrations.AddField(
            model_name='evaluacionentrega',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='evaluacionentrega',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='actividadcronograma',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma_actividades_evaluador', to='administrador.evento'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_evaluador', to='administrador.evento'),
        ),
        migrations.AddField(
            model_name='evaluacionasignacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_asignadas_evaluador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacionentrega',
            name='asignacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='evaluador.evaluacionasignacion'),
        ),
        migrations.AddIndex(
            model_name='evaluacionentrega',
            index=models.Index(fields=['fecha_envio'], name='evaluador_e_fecha_e_330884_idx'),
        ),
        migrations.AddField(
            model_name='evaluacionproyecto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_proyectos_evaluador', to='administrador.evento'),
        ),
        migrations.AddField(
            model_name='evaluacionasignacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='evaluador.evaluacionproyecto'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios', to='evaluador.evaluacionproyecto'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_evaluador', to='administrador.evento'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_evento_evaluador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_evaluador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados_evaluador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_evaluador', to='administrador.evento'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='evaluador.evaluacionproyecto'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas_evaluador', to='administrador.evento'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubricas', to='evaluador.evaluacionproyecto'),
        ),
        migrations.AddField(
            model_name='rubricaadjunto',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='evaluador.rubrica'),
        ),
        migrations.AddField(
            model_name='rubricacriterio',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='evaluador.rubrica'),
        ),
        migrations.RemoveField(
            model_name='evaluacionentrega',
            name='puntaje_total',
        ),
        migrations.AddIndex(
            model_name='actividadcronograma',
            index=models.Index(fields=['evento', 'inicio', 'fin'], name='evaluador_a_evento__568c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionproyecto',
            index=models.Index(fields=['evento', 'inicio', 'fin'], name='evaluador_e_evento__fea9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionasignacion',
            index=models.Index(fields=['evaluador'], name='evaluador_e_evaluad_2ebc67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionasignacion',
            unique_together={('proyecto', 'evaluador')},
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['evento', 'tipo'], name='evaluador_e_evento__fbf07f_idx'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['evento', 'estado'], name='evaluador_e_evento__4553e0_idx'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['evento', 'nombre'], name='evaluador_e_evento__df13e9_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['evento', 'rol'], name='evaluador_i_evento__64b1cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('evento', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['usuario'], name='evaluador_p_usuario_9a06b8_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['evento', 'categoria'], name='evaluador_r_evento__9a8c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['evento', 'estado'], name='evaluador_r_evento__9bbf89_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['evento', 'generado_en'], name='evaluador_r_evento__6db9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='rubrica',
            index=models.Index(fields=['evento', 'estado'], name='evaluador_r_evento__2933a0_idx'),
        ),
        migrations.AddIndex(
            model_name='rubrica',
            index=models.Index(fields=['evento', 'proyecto'], name='evaluador_r_evento__10ab4d_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricacriterio',
            index=models.Index(fields=['rubrica', 'orden'], name='evaluador_r_rubrica_a28efa_idx'),
        ),
    ]
