# Generated by Django 6.0.2 on 2026-03-20 03:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluador', '0002_actividadcronograma_espacio_evaluacionasignacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionRespuestaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('valor', models.PositiveSmallIntegerField(default=1)),
                ('observacion', models.TextField(blank=True, default='')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_evaluador', to='evaluador.rubricacriterio')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluador.evaluacionentrega')),
            ],
            options={
                'ordering': ['criterio__orden', 'criterio_id', 'id'],
                'indexes': [models.Index(fields=['entrega', 'criterio'], name='evaluador_e_entrega_e47258_idx'), models.Index(fields=['criterio'], name='evaluador_e_criteri_8213f9_idx')],
                'unique_together': {('entrega', 'criterio')},
            },
        ),
    ]
