# Generated by Django 6.0.2 on 2026-03-24 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0012_alter_espacio_options_remove_rubrica_modo_captura_and_more'),
        ('evaluador', '0003_evaluacionrespuestacriterio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionentrega',
            name='asignacion_canonica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrega_evaluador_migrada', to='coordinador.evaluacionasignacion'),
        ),
        migrations.AddField(
            model_name='evaluacionrespuestacriterio',
            name='criterio_canonico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_evaluador_migradas', to='coordinador.rubricacriterio'),
        ),
        migrations.AddIndex(
            model_name='evaluacionrespuestacriterio',
            index=models.Index(fields=['criterio_canonico'], name='evaluador_e_criteri_f09f79_idx'),
        ),
    ]
