# Generated by Django 6.0.2 on 2026-02-25 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('lugar', models.CharField(blank=True, max_length=255)),
                ('responsable', models.CharField(blank=True, max_length=255)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='administrador.evento')),
            ],
            options={
                'ordering': ['orden', 'inicio'],
            },
        ),
    ]
