# Generated by Django 6.0.2 on 2026-02-26 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('coordinador', '0002_alter_actividadcronograma_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadcronograma',
            options={'ordering': ('inicio', 'fin', 'id')},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ('-creado_en',)},
        ),
        migrations.RemoveField(
            model_name='actividadcronograma',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='actividadcronograma',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='actividadcronograma',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='estado',
        ),
        migrations.AddField(
            model_name='actividadcronograma',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_cronograma', to='administrador.evento'),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='titulo',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COOR', 'Coordinador'), ('PON', 'Ponente'), ('PART', 'Participante'), ('EVAL', 'Evaluador')], default='PART', max_length=10),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_evento', to=settings.AUTH_USER_MODEL),
        ),
    ]
