# Generated by Django 6.0.2 on 2026-02-27 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('coordinador', '0003_alter_actividadcronograma_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=220)),
                ('ponente', models.CharField(blank=True, default='', max_length=180)),
                ('lugar', models.CharField(blank=True, default='', max_length=180)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
            ],
            options={
                'ordering': ['inicio', 'fin', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='actividadcronograma',
            options={'ordering': ['inicio', 'fin', 'id']},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={},
        ),
        migrations.RemoveField(
            model_name='actividadcronograma',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='actividadcronograma',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma_actividades', to='administrador.evento'),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COORDINADOR', 'Coordinador'), ('EVALUADOR', 'Evaluador'), ('PONENTE', 'Ponente'), ('PARTICIPANTE', 'Participante')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='actividadcronograma',
            index=models.Index(fields=['evento', 'inicio', 'fin'], name='coordinador_evento__581c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['evento', 'rol'], name='coordinador_evento__11f689_idx'),
        ),
        migrations.AddField(
            model_name='evaluacionasignacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_evaluacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacionproyecto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_proyectos', to='administrador.evento'),
        ),
        migrations.AddField(
            model_name='evaluacionasignacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='coordinador.evaluacionproyecto'),
        ),
        migrations.AddIndex(
            model_name='evaluacionproyecto',
            index=models.Index(fields=['evento', 'inicio', 'fin'], name='coordinador_evento__6f0452_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionasignacion',
            index=models.Index(fields=['evaluador'], name='coordinador_evaluad_4f4606_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionasignacion',
            index=models.Index(fields=['proyecto'], name='coordinador_proyect_d7fa47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionasignacion',
            unique_together={('proyecto', 'evaluador')},
        ),
    ]
