# Generated by Django 6.0.2 on 2026-02-27 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('coordinador', '0004_evaluacionasignacion_evaluacionproyecto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionasignacion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='actividadcronograma',
            name='coordinador_evento__581c5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='evaluacionasignacion',
            name='coordinador_evaluad_4f4606_idx',
        ),
        migrations.RemoveIndex(
            model_name='evaluacionasignacion',
            name='coordinador_proyect_d7fa47_idx',
        ),
        migrations.RemoveIndex(
            model_name='evaluacionproyecto',
            name='coordinador_evento__6f0452_idx',
        ),
        migrations.RemoveIndex(
            model_name='inscripcion',
            name='coordinador_evento__11f689_idx',
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_cronograma', to='administrador.evento'),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='responsable',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='evaluacionasignacion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluacionasignacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_evaluador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacionproyecto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluacionproyecto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_evaluacion', to='administrador.evento'),
        ),
        migrations.AlterField(
            model_name='evaluacionproyecto',
            name='lugar',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='evaluacionproyecto',
            name='ponente',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COORDINADOR', 'Coordinador'), ('EVALUADOR', 'Evaluador'), ('PONENTE', 'Ponente'), ('PARTICIPANTE', 'Participante'), ('USUARIO', 'Usuario')], default='PARTICIPANTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_coordinador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='evaluacionasignacion',
            name='actualizado_en',
        ),
    ]
