# Generated by Django 6.0.2 on 2026-03-01 06:44

import coordinador.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('coordinador', '0005_alter_evaluacionasignacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=220)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa')], default='BORRADOR', max_length=20)),
            ],
            options={
                'ordering': ['-actualizado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RubricaAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to=coordinador.models.rubrica_upload_path)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('tamano', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RubricaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('puntaje_max', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='evaluacionasignacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={},
        ),
        migrations.AddField(
            model_name='evaluacionasignacion',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma_actividades', to='administrador.evento'),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='evaluacionasignacion',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='evaluacionasignacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacionproyecto',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='evaluacionproyecto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_proyectos', to='administrador.evento'),
        ),
        migrations.AlterField(
            model_name='evaluacionproyecto',
            name='lugar',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='evaluacionproyecto',
            name='ponente',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COORDINADOR', 'Coordinador'), ('USUARIO', 'Usuario'), ('EVALUADOR', 'Evaluador'), ('PONENTE', 'Ponente'), ('PARTICIPANTE', 'Participante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_evento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='actividadcronograma',
            index=models.Index(fields=['evento', 'inicio', 'fin'], name='coordinador_evento__581c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionasignacion',
            index=models.Index(fields=['evaluador'], name='coordinador_evaluad_4f4606_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionproyecto',
            index=models.Index(fields=['evento', 'inicio', 'fin'], name='coordinador_evento__6f0452_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['evento', 'rol'], name='coordinador_evento__11f689_idx'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='administrador.evento'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubricas', to='coordinador.evaluacionproyecto'),
        ),
        migrations.AddField(
            model_name='rubricaadjunto',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='coordinador.rubrica'),
        ),
        migrations.AddField(
            model_name='rubricacriterio',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='coordinador.rubrica'),
        ),
        migrations.AddIndex(
            model_name='rubrica',
            index=models.Index(fields=['evento', 'estado'], name='coordinador_evento__adc648_idx'),
        ),
        migrations.AddIndex(
            model_name='rubrica',
            index=models.Index(fields=['evento', 'proyecto'], name='coordinador_evento__c2a4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricaadjunto',
            index=models.Index(fields=['rubrica'], name='coordinador_rubrica_441000_idx'),
        ),
        migrations.AddIndex(
            model_name='rubricacriterio',
            index=models.Index(fields=['rubrica', 'orden'], name='coordinador_rubrica_d78d84_idx'),
        ),
    ]
