# Generated by Django 6.0.2 on 2026-03-01 23:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('coordinador', '0006_rubrica_rubricaadjunto_rubricacriterio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('AUDITORIO', 'Auditorio'), ('SALA', 'Sala'), ('LABORATORIO', 'Laboratorio'), ('VIRTUAL', 'Virtual')], default='SALA', max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=220)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('tags', models.CharField(blank=True, default='', max_length=240)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='administrador.evento')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios', to='coordinador.evaluacionproyecto')),
            ],
            options={
                'ordering': ['-actualizado_en', '-id'],
                'indexes': [models.Index(fields=['evento', 'estado'], name='coordinador_evento__17ea1a_idx'), models.Index(fields=['evento', 'tipo'], name='coordinador_evento__916875_idx'), models.Index(fields=['evento', 'proyecto'], name='coordinador_evento__44c0ac_idx')],
            },
        ),
    ]
