# Generated by Django 6.0.2 on 2026-03-02 01:48

import coordinador.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('coordinador', '0007_espacio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=220)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.CharField(choices=[('TODOS', 'Todos'), ('INSCRIPCIONES', 'Inscripciones'), ('EVALUACIONES', 'Evaluaciones'), ('ASISTENCIA', 'Asistencia'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel (XLSX)')], default='PDF', max_length=10)),
                ('modo', models.CharField(choices=[('TIEMPO_REAL', 'Tiempo real'), ('HISTORIAL', 'Historial')], default='TIEMPO_REAL', max_length=20)),
                ('estado', models.CharField(choices=[('LISTO', 'Listo'), ('ARCHIVADO', 'Archivado')], default='LISTO', max_length=20)),
                ('generado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=coordinador.models.reporte_upload_path)),
            ],
            options={
                'ordering': ['-generado_en', '-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='espacio',
            name='coordinador_evento__44c0ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='rubricaadjunto',
            name='coordinador_rubrica_441000_idx',
        ),
        migrations.AlterField(
            model_name='espacio',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='tipo',
            field=models.CharField(choices=[('AUDITORIO', 'Auditorio'), ('SALA', 'Sala'), ('LABORATORIO', 'Laboratorio'), ('OTRO', 'Otro')], default='SALA', max_length=20),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['evento', 'nombre'], name='coordinador_evento__131549_idx'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='administrador.evento'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='coordinador.evaluacionproyecto'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['evento', 'categoria'], name='coordinador_evento__8b330a_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['evento', 'estado'], name='coordinador_evento__b91152_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['evento', 'generado_en'], name='coordinador_evento__d4e820_idx'),
        ),
    ]
