# Generated by Django 6.0.2 on 2026-03-02 02:53

import coordinador.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0008_reporte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('puesto', models.CharField(blank=True, default='', max_length=120)),
                ('institucion', models.CharField(blank=True, default='', max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=coordinador.models._avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), coordinador.models.validate_avatar_size])),
                ('cv', models.FileField(blank=True, null=True, upload_to=coordinador.models._cv_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), coordinador.models.validate_cv_size])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario'], name='coordinador_usuario_03b090_idx')],
            },
        ),
    ]
