# Generated by Django 6.0.2 on 2026-03-18 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auditorialog_accion_tipo_auditorialog_detalles_and_more'),
        ('coordinador', '0009_perfilusuario'),
        ('ponente', '0008_remove_ponencia_uq_ponencia_evento_ponente_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='ponencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubricas', to='ponente.ponencia'),
        ),
        migrations.AddIndex(
            model_name='rubrica',
            index=models.Index(fields=['evento', 'ponencia'], name='coordinador_evento__cec5a7_idx'),
        ),
    ]
