# Generated by Django 6.0.2 on 2026-03-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0010_rubrica_ponencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='modo_captura',
            field=models.CharField(choices=[('MANUAL', 'Captura manual'), ('IMPORTAR', 'Importar archivo')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='rubricaadjunto',
            name='es_fuente',
            field=models.BooleanField(default=False),
        ),
    ]
