# Generated by Django 6.0.2 on 2026-03-19 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auditorialog_accion_tipo_auditorialog_detalles_and_more'),
        ('coordinador', '0011_rubrica_modo_captura_rubricaadjunto_es_fuente'),
        ('ponente', '0008_remove_ponencia_uq_ponencia_evento_ponente_titulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacio',
            options={'ordering': ['inicio', 'fin', 'nombre', 'id']},
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='modo_captura',
        ),
        migrations.RemoveField(
            model_name='rubricaadjunto',
            name='es_fuente',
        ),
        migrations.AddField(
            model_name='espacio',
            name='fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='ponencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios_asignados', to='ponente.ponencia'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['evento', 'inicio', 'fin'], name='coordinador_evento__61f2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['evento', 'proyecto'], name='coordinador_evento__44c0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['evento', 'ponencia'], name='coordinador_evento__947e54_idx'),
        ),
    ]
