# Generated by Django 6.0.2 on 2026-03-17 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorialog',
            name='accion_tipo',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='detalles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='entidad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='modulo',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='objeto_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='resultado',
            field=models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('ADVERTENCIA', 'Advertencia')], db_index=True, default='EXITOSO', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=15),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['-fecha'], name='administrad_fecha_c64365_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['modulo', 'accion_tipo'], name='administrad_modulo_ab8036_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['resultado', 'fecha'], name='administrad_resulta_24a523_idx'),
        ),
    ]
