# Generated by Django 6.0.2 on 2026-03-09 01:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import participante.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('institucion', models.CharField(blank=True, default='', max_length=180)),
                ('carrera', models.CharField(blank=True, default='', max_length=180)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=participante.models.upload_avatar, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), participante.models.validate_avatar_file])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilparticipante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de participante',
                'verbose_name_plural': 'Perfiles de participantes',
            },
        ),
        migrations.CreateModel(
            name='InscripcionParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado_inscripcion', models.CharField(choices=[('PREINSCRITO', 'Preinscrito'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], default='PREINSCRITO', max_length=20)),
                ('folio_inscripcion', models.CharField(blank=True, default='', max_length=50)),
                ('codigo_pase', models.CharField(blank=True, default='', max_length=80)),
                ('tipo_acceso', models.CharField(blank=True, default='Participante', max_length=100)),
                ('pase_generado_en', models.DateTimeField(blank=True, null=True)),
                ('asistencia_confirmada', models.BooleanField(default=False)),
                ('constancia_habilitada', models.BooleanField(default=False)),
                ('folio_constancia', models.CharField(blank=True, default='', max_length=50)),
                ('constancia_generada_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_participantes', to='administrador.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_participante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción de participante',
                'verbose_name_plural': 'Inscripciones de participantes',
                'ordering': ['-actualizado_en', '-id'],
                'indexes': [models.Index(fields=['participante', 'evento'], name='participant_partici_910cea_idx'), models.Index(fields=['estado_inscripcion'], name='participant_estado__58d47e_idx'), models.Index(fields=['constancia_habilitada'], name='participant_constan_af0b73_idx'), models.Index(fields=['asistencia_confirmada'], name='participant_asisten_43a7f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('participante', 'evento'), name='uq_inscripcion_participante_evento')],
            },
        ),
    ]
