# Generated by Django 6.0.2 on 2026-03-22 00:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import participante.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0002_auditorialog_accion_tipo_auditorialog_detalles_and_more'),
        ('evaluador', '0003_evaluacionrespuestacriterio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('institucion', models.CharField(blank=True, default='', max_length=180)),
                ('biografia', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=participante.models.upload_avatar)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_participante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de participante',
                'verbose_name_plural': 'Perfiles de participantes',
            },
        ),
        migrations.CreateModel(
            name='ProyectoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_participante', models.CharField(max_length=180)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('institucion_empresa', models.CharField(max_length=200)),
                ('nombre_proyecto', models.CharField(max_length=220)),
                ('categoria', models.CharField(choices=[('TECNOLOGIA', 'Tecnología'), ('INNOVACION', 'Innovación'), ('INVESTIGACION', 'Investigación'), ('SOCIAL', 'Impacto social'), ('EMPRESARIAL', 'Emprendimiento')], max_length=20)),
                ('numero_integrantes', models.PositiveIntegerField(default=1)),
                ('resumen', models.TextField(blank=True, default='')),
                ('presentacion', models.FileField(blank=True, null=True, upload_to=participante.models.upload_presentacion, validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptx']), participante.models.validate_presentacion_size])),
                ('informe', models.FileField(blank=True, null=True, upload_to=participante.models.upload_informe, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), participante.models.validate_informe_size])),
                ('requerimientos_tecnicos', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_REVISION', 'En revisión'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='REGISTRADO', max_length=20)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('espacio_asignado', models.CharField(blank=True, default='', max_length=180)),
                ('estado_programacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRAMADO', 'Programado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('evaluacion_proyecto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto_real', to='evaluador.evaluacionproyecto')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_participantes', to='administrador.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_participante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto participante',
                'verbose_name_plural': 'Proyectos participantes',
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['evento', 'estado'], name='participant_evento__ba53a9_idx'), models.Index(fields=['participante', 'evento'], name='participant_partici_271fed_idx')],
                'constraints': [models.UniqueConstraint(fields=('evento', 'participante'), name='unique_proyecto_por_evento_y_participante')],
            },
        ),
    ]
