# Generated by Django 6.0.2 on 2026-03-22 05:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaseAccesoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('total_escaneos', models.PositiveIntegerField(default=0)),
                ('ultimo_escaneo', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pase_acceso', to='participante.proyectoparticipante')),
            ],
            options={
                'verbose_name': 'Pase de acceso de participante',
                'verbose_name_plural': 'Pases de acceso de participantes',
                'ordering': ['-actualizado_en', '-id'],
            },
        ),
    ]
