# Generated by Django 6.0.2 on 2026-03-22 06:12

import django.db.models.deletion
import django.utils.timezone
import participante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0002_paseaccesoparticipante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(db_index=True, default=participante.models.generar_folio_constancia, editable=False, max_length=40, unique=True)),
                ('emitida_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constancia_generada', to='participante.proyectoparticipante')),
            ],
            options={
                'verbose_name': 'Constancia de participante',
                'verbose_name_plural': 'Constancias de participantes',
                'ordering': ['-emitida_en', '-id'],
            },
        ),
    ]
