# Generated by Django 6.0.2 on 2026-03-22 06:31

import django.core.validators
import participante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0003_constanciaparticipante'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilparticipante',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=participante.models.upload_cv, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), participante.models.validate_cv_size]),
        ),
    ]
